apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiApp-deployment
spec:
  selector:
    matchLabels:
      app: apiApp
  template:
    metadata:
      labels:
        app: apiApp
    spec:
      containers:
      - name: apiApp
        image: 328440967566.dkr.ecr.us-east-1.amazonaws.com/apiApp
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
