apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- range $key, $val := .Values.metadata.labels }}
      {{ $key }}: {{ $val | quote}}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $val := .Values.metadata.labels }}
        {{ $key }}: {{ $val | quote}}
      {{- end }}
  template:
    metadata:
      name: {{ .Values.metadata.name }}
      labels:
        {{- range $key, $val := .Values.metadata.labels }}
          {{ $key }}: {{ $val | quote}}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.metadata.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP